"""talent_inventory

Revision ID: 070d60b1b9d5
Revises: 3e85e9b6b395
Create Date: 2026-09-29 08:14:28.872910
"""
from alembic import op
import sqlalchemy as sa

import app.models.types


revision = '070d60b1b9d5'
down_revision = '3e85e9b6b395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.Enum('ANNUAL', 'SUCCESSION', 'SALARY', 'DEVELOPMENT', name='inventorypurpose'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CALIBRATING', 'CONFIRMING', 'PUBLISHED', name='batchstatus'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('scope_employee_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('published_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_batches_tenant_id'), 'inventory_batches', ['tenant_id'], unique=False)
    op.create_table('inventory_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('perf_label', sa.String(length=4), nullable=True),
    sa.Column('ability_score', sa.Integer(), nullable=True),
    sa.Column('potential', sa.Enum('HIGH', 'MID', 'LOW', name='potential'), nullable=True),
    sa.Column('potential_by', sa.Uuid(), nullable=True),
    sa.Column('potential_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('grid_code', sa.String(length=4), nullable=True),
    sa.Column('located', sa.Boolean(), nullable=False),
    sa.Column('calibrate_note', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'employee_id', name='inventory_results_batch_employee_uc')
    )
    op.create_index(op.f('ix_inventory_results_batch_id'), 'inventory_results', ['batch_id'], unique=False)
    op.create_index(op.f('ix_inventory_results_employee_id'), 'inventory_results', ['employee_id'], unique=False)
    op.alter_column('employees', 'perf_grade',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'perf_grade',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.drop_index(op.f('ix_inventory_results_employee_id'), table_name='inventory_results')
    op.drop_index(op.f('ix_inventory_results_batch_id'), table_name='inventory_results')
    op.drop_table('inventory_results')
    op.drop_index(op.f('ix_inventory_batches_tenant_id'), table_name='inventory_batches')
    op.drop_table('inventory_batches')
    sa.Enum(name='potential').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='batchstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='inventorypurpose').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
