"""talent_profile

Revision ID: 3e85e9b6b395
Revises: d92cc0e629f8
Create Date: 2026-09-29 08:01:51.930566
"""
from alembic import op
import sqlalchemy as sa

import app.models.types


revision = '3e85e9b6b395'
down_revision = 'd92cc0e629f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('version_seq', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'CERT_WRITEBACK', name='profilesource'), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('generated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_snapshots_employee_id'), 'profile_snapshots', ['employee_id'], unique=False)
    op.create_index(op.f('ix_profile_snapshots_tenant_id'), 'profile_snapshots', ['tenant_id'], unique=False)
    op.create_table('profile_dimensions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('dimension_key', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('MEASURED', 'NO_DATA', name='dimensionstatus'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('grade_label', sa.String(length=16), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_ref', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_snapshot_id'], ['profile_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_snapshot_id', 'dimension_key', name='profile_dimensions_snapshot_key_uc')
    )
    op.create_index(op.f('ix_profile_dimensions_profile_snapshot_id'), 'profile_dimensions', ['profile_snapshot_id'], unique=False)
    op.add_column('employees', sa.Column('education', sa.String(length=32), nullable=True))
    op.add_column('employees', sa.Column('certificates', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('employees', sa.Column('basic_updated_by', sa.Uuid(), nullable=True))
    op.add_column('employees', sa.Column('basic_updated_at', app.models.types.UTCDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'basic_updated_at')
    op.drop_column('employees', 'basic_updated_by')
    op.drop_column('employees', 'certificates')
    op.drop_column('employees', 'education')
    op.drop_index(op.f('ix_profile_dimensions_profile_snapshot_id'), table_name='profile_dimensions')
    op.drop_table('profile_dimensions')
    op.drop_index(op.f('ix_profile_snapshots_tenant_id'), table_name='profile_snapshots')
    op.drop_index(op.f('ix_profile_snapshots_employee_id'), table_name='profile_snapshots')
    op.drop_table('profile_snapshots')
    sa.Enum(name='dimensionstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='profilesource').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
