"""p2 compensation incentive tables

Revision ID: 776893e567e2
Revises: d4f6a2b8c1e3
Create Date: 2026-10-05 21:00:11.476379
"""
from alembic import op
import sqlalchemy as sa

from app.models.types import UTCDateTime


revision = '776893e567e2'
down_revision = 'd4f6a2b8c1e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjustment_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('perf_plan_id', sa.Uuid(), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('adjustments', sa.JSON(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('approved_at', UTCDateTime(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['perf_plan_id'], ['perf_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjustment_plans_perf_plan_id'), 'adjustment_plans', ['perf_plan_id'], unique=False)
    op.create_index(op.f('ix_adjustment_plans_tenant_id'), 'adjustment_plans', ['tenant_id'], unique=False)
    op.create_table('bonus_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('perf_plan_id', sa.Uuid(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('bonus_pool_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('proration_enabled', sa.Boolean(), nullable=False),
    sa.Column('scope_depts', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('approved_at', UTCDateTime(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['perf_plan_id'], ['perf_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_plans_perf_plan_id'), 'bonus_plans', ['perf_plan_id'], unique=False)
    op.create_index(op.f('ix_bonus_plans_tenant_id'), 'bonus_plans', ['tenant_id'], unique=False)
    op.create_table('bonus_dept_pools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('dept_id', sa.String(length=32), nullable=False),
    sa.Column('target_sum', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('formula_sum', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pool_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('adjust_reason', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['bonus_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_dept_pools_plan_id'), 'bonus_dept_pools', ['plan_id'], unique=False)
    op.create_index(op.f('ix_bonus_dept_pools_tenant_id'), 'bonus_dept_pools', ['tenant_id'], unique=False)
    op.create_table('salary_adjustment_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('old_salary', sa.Integer(), nullable=False),
    sa.Column('new_salary', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_plan_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_adjustment_history_employee_id'), 'salary_adjustment_history', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salary_adjustment_history_source_plan_id'), 'salary_adjustment_history', ['source_plan_id'], unique=False)
    op.create_index(op.f('ix_salary_adjustment_history_tenant_id'), 'salary_adjustment_history', ['tenant_id'], unique=False)
    op.create_table('bonus_plan_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('target_bonus', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('perf_coefficient', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('org_coefficient', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('service_months', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('formula_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dept_pool_id', sa.Uuid(), nullable=True),
    sa.Column('scale_ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('excluded_reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dept_pool_id'], ['bonus_dept_pools.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['bonus_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'employee_id', name='uq_bonus_item_plan_employee')
    )
    op.create_index(op.f('ix_bonus_plan_items_dept_pool_id'), 'bonus_plan_items', ['dept_pool_id'], unique=False)
    op.create_index(op.f('ix_bonus_plan_items_employee_id'), 'bonus_plan_items', ['employee_id'], unique=False)
    op.create_index(op.f('ix_bonus_plan_items_plan_id'), 'bonus_plan_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_bonus_plan_items_tenant_id'), 'bonus_plan_items', ['tenant_id'], unique=False)
    op.add_column('tenant_salary_bands', sa.Column('p25', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('tenant_salary_bands', sa.Column('p50', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('tenant_salary_bands', sa.Column('p75', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('tenant_salary_bands', sa.Column('p90', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('tenant_salary_bands', sa.Column('market_source_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_salary_bands', 'market_source_year')
    op.drop_column('tenant_salary_bands', 'p90')
    op.drop_column('tenant_salary_bands', 'p75')
    op.drop_column('tenant_salary_bands', 'p50')
    op.drop_column('tenant_salary_bands', 'p25')
    op.drop_index(op.f('ix_bonus_plan_items_tenant_id'), table_name='bonus_plan_items')
    op.drop_index(op.f('ix_bonus_plan_items_plan_id'), table_name='bonus_plan_items')
    op.drop_index(op.f('ix_bonus_plan_items_employee_id'), table_name='bonus_plan_items')
    op.drop_index(op.f('ix_bonus_plan_items_dept_pool_id'), table_name='bonus_plan_items')
    op.drop_table('bonus_plan_items')
    op.drop_index(op.f('ix_salary_adjustment_history_tenant_id'), table_name='salary_adjustment_history')
    op.drop_index(op.f('ix_salary_adjustment_history_source_plan_id'), table_name='salary_adjustment_history')
    op.drop_index(op.f('ix_salary_adjustment_history_employee_id'), table_name='salary_adjustment_history')
    op.drop_table('salary_adjustment_history')
    op.drop_index(op.f('ix_bonus_dept_pools_tenant_id'), table_name='bonus_dept_pools')
    op.drop_index(op.f('ix_bonus_dept_pools_plan_id'), table_name='bonus_dept_pools')
    op.drop_table('bonus_dept_pools')
    op.drop_index(op.f('ix_bonus_plans_tenant_id'), table_name='bonus_plans')
    op.drop_index(op.f('ix_bonus_plans_perf_plan_id'), table_name='bonus_plans')
    op.drop_table('bonus_plans')
    op.drop_index(op.f('ix_adjustment_plans_tenant_id'), table_name='adjustment_plans')
    op.drop_index(op.f('ix_adjustment_plans_perf_plan_id'), table_name='adjustment_plans')
    op.drop_table('adjustment_plans')
    # ### end Alembic commands ###
