"""add_gap_and_org_diagnosis_tables

Revision ID: 841474803e36
Revises: b19c54eeb509
Create Date: 2026-09-29 11:07:04.832107
"""
from alembic import op
import sqlalchemy as sa
import app.models.types  # noqa: F401 — UTCDateTime used below


revision = '841474803e36'
down_revision = 'b19c54eeb509'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquid_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dept_name', sa.String(length=64), nullable=False),
    sa.Column('needs', sa.JSON(), nullable=False),
    sa.Column('deadline', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('FORMING', 'RUNNING', name='liquidprojectstatus'), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquid_projects_tenant_id'), 'liquid_projects', ['tenant_id'], unique=False)
    op.create_table('gaps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.Enum('PERF', 'DUTY', 'ABILITY', 'CONTRIBUTION', 'KNOWLEDGE', name='gapdimension'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('standard', sa.Text(), nullable=False),
    sa.Column('current', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('HIGH', 'MID', 'LOW', name='gapseverity'), nullable=False),
    sa.Column('action', sa.Enum('PERF_IMPROVEMENT', 'PROCESS_SUPERVISION', 'BEHAVIOR_IMPROVE', 'TEAM_CONTRIBUTION', 'LEARN_KNOWLEDGE', name='gapaction'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gaps_employee_id'), 'gaps', ['employee_id'], unique=False)
    op.create_index(op.f('ix_gaps_tenant_id'), 'gaps', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gaps_tenant_id'), table_name='gaps')
    op.drop_index(op.f('ix_gaps_employee_id'), table_name='gaps')
    op.drop_table('gaps')
    op.drop_index(op.f('ix_liquid_projects_tenant_id'), table_name='liquid_projects')
    op.drop_table('liquid_projects')
    # ### end Alembic commands ###
