"""add_recruit_tables

Revision ID: b19c54eeb509
Revises: ce272281bded
Create Date: 2026-09-29 10:57:36.835907
"""
from alembic import op
import sqlalchemy as sa
from app.models.types import UTCDateTime


revision = 'b19c54eeb509'
down_revision = 'ce272281bded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=128), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_point', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'STANDARD', 'AI', name='questionsource'), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'PENDING_REVIEW', 'REJECTED', name='questionstatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_tenant_id'), 'interview_questions', ['tenant_id'], unique=False)
    op.create_table('requisitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.String(length=128), nullable=False),
    sa.Column('dept_id', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('funnel', sa.JSON(), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('opened_at', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisitions_tenant_id'), 'requisitions', ['tenant_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('req_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.Enum('SCREEN', 'FIRST', 'FINAL', 'OFFER', 'ONBOARD', 'REJECTED', name='candstage'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('last_title', sa.String(length=128), nullable=False),
    sa.Column('expected_salary', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Double(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['req_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_req_id'), 'candidates', ['req_id'], unique=False)
    op.create_index(op.f('ix_candidates_tenant_id'), 'candidates', ['tenant_id'], unique=False)
    op.create_table('interview_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('req_id', sa.Uuid(), nullable=True),
    sa.Column('interviewer_id', sa.Uuid(), nullable=False),
    sa.Column('dimension_scores', sa.JSON(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rating', sa.Double(), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['req_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_records_candidate_id'), 'interview_records', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interview_records_tenant_id'), 'interview_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_records_tenant_id'), table_name='interview_records')
    op.drop_index(op.f('ix_interview_records_candidate_id'), table_name='interview_records')
    op.drop_table('interview_records')
    op.drop_index(op.f('ix_candidates_tenant_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_req_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_requisitions_tenant_id'), table_name='requisitions')
    op.drop_table('requisitions')
    op.drop_index(op.f('ix_interview_questions_tenant_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    # ### end Alembic commands ###
