"""initial schema

Revision ID: c98f651f7225
Revises: 
Create Date: 2026-09-28 23:13:15.539731
"""
from alembic import op
import sqlalchemy as sa

import app.models.types


revision = 'c98f651f7225'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.String(length=32), nullable=False),
    sa.Column('target_grade', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='standardstatus'), nullable=False),
    sa.Column('published_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_sets_sequence'), 'standard_sets', ['sequence'], unique=False)
    op.create_index(op.f('ix_standard_sets_tenant_id'), 'standard_sets', ['tenant_id'], unique=False)
    op.create_table('tenant_configs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('standard_set_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['standard_set_id'], ['standard_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_items_standard_set_id'), 'standard_items', ['standard_set_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'MANAGER', 'REVIEWER', 'LEAD_REVIEWER', 'HR', 'TENANT_ADMIN', 'PLATFORM_ADMIN', name='role'), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('employee_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('dept_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.String(length=128), nullable=False),
    sa.Column('family', sa.String(length=8), nullable=False),
    sa.Column('sequence', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('grade_since', sa.Date(), nullable=False),
    sa.Column('perf_grade', sa.String(length=4), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('target_sequence', sa.String(length=32), nullable=False),
    sa.Column('target_grade', sa.String(length=32), nullable=False),
    sa.Column('standard_set_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'IN_MANAGER_REVIEW', 'IN_COMMITTEE_REVIEW', 'APPROVED', 'REJECTED', 'PUBLISHED', name='applicationstatus'), nullable=False),
    sa.Column('previous_application_id', sa.Uuid(), nullable=True),
    sa.Column('submit_count', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('manager_deadline_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('submitted_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('manager_reviewed_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('decided_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('published_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('review_locked_by', sa.Uuid(), nullable=True),
    sa.Column('review_locked_until', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['previous_application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['review_locked_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['standard_set_id'], ['standard_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_employee_id'), 'applications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_applications_tenant_id'), 'applications', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_table('review_panel_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.String(length=32), nullable=False),
    sa.Column('lead_reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_ids', app.models.types.GUIDList(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_reviewer_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_panel_templates_sequence'), 'review_panel_templates', ['sequence'], unique=False)
    op.create_index(op.f('ix_review_panel_templates_tenant_id'), 'review_panel_templates', ['tenant_id'], unique=False)
    op.create_table('ai_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('opinion', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestions_application_id'), 'ai_suggestions', ['application_id'], unique=True)
    op.create_table('ai_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_application_id'), 'ai_usage', ['application_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_tenant_id'), 'ai_usage', ['tenant_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('standard_item_code', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint("mime_type IN ('image/jpeg','image/png','application/pdf')", name='evidence_mime_type_check'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_application_id'), 'evidences', ['application_id'], unique=False)
    op.create_index(op.f('ix_evidences_standard_item_code'), 'evidences', ['standard_item_code'], unique=False)
    op.create_table('manager_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reject_category', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_reviews_application_id'), 'manager_reviews', ['application_id'], unique=True)
    op.create_table('review_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('opinion', sa.Text(), nullable=True),
    sa.Column('submitted_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'assignee_id', name='review_tasks_application_assignee_uc')
    )
    op.create_index(op.f('ix_review_tasks_application_id'), 'review_tasks', ['application_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_assignee_id'), 'review_tasks', ['assignee_id'], unique=False)
    op.create_table('self_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('standard_item_code', sa.String(length=64), nullable=False),
    sa.Column('self_level', sa.Enum('MET', 'PARTIALLY_MET', 'NOT_MET', name='selflevel'), nullable=False),
    sa.Column('self_comment', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'standard_item_code')
    )
    op.create_index(op.f('ix_self_assessments_application_id'), 'self_assessments', ['application_id'], unique=False)
    op.create_table('standard_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('standard_set_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_snapshots_application_id'), 'standard_snapshots', ['application_id'], unique=True)
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.Column('ai_suggestion_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_suggestion_id'], ['ai_suggestions.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_application_id'), 'decisions', ['application_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_application_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_standard_snapshots_application_id'), table_name='standard_snapshots')
    op.drop_table('standard_snapshots')
    op.drop_index(op.f('ix_self_assessments_application_id'), table_name='self_assessments')
    op.drop_table('self_assessments')
    op.drop_index(op.f('ix_review_tasks_assignee_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_application_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_manager_reviews_application_id'), table_name='manager_reviews')
    op.drop_table('manager_reviews')
    op.drop_index(op.f('ix_evidences_standard_item_code'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_application_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_ai_usage_tenant_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_application_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_ai_suggestions_application_id'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.drop_index(op.f('ix_review_panel_templates_tenant_id'), table_name='review_panel_templates')
    op.drop_index(op.f('ix_review_panel_templates_sequence'), table_name='review_panel_templates')
    op.drop_table('review_panel_templates')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_applications_tenant_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_employee_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_standard_items_standard_set_id'), table_name='standard_items')
    op.drop_table('standard_items')
    op.drop_table('tenants')
    op.drop_table('tenant_configs')
    op.drop_index(op.f('ix_standard_sets_tenant_id'), table_name='standard_sets')
    op.drop_index(op.f('ix_standard_sets_sequence'), table_name='standard_sets')
    op.drop_table('standard_sets')
    # Drop the pg ENUM types created alongside the tables
    for enum_name in ('standardstatus', 'role', 'applicationstatus', 'selflevel'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
