"""add idps table

Revision ID: ce272281bded
Revises: dcedd2ea1fa6
Create Date: 2026-09-29 09:46:40.235202
"""
from alembic import op
import sqlalchemy as sa

from app.models.types import UTCDateTime


revision = 'ce272281bded'
down_revision = 'dcedd2ea1fa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('period_type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'REVIEWING', 'CLOSED', name='idpstatus'), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('key_behaviors', sa.JSON(), nullable=False),
    sa.Column('review_result', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idps_employee_id'), 'idps', ['employee_id'], unique=False)
    op.create_index(op.f('ix_idps_tenant_id'), 'idps', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idps_tenant_id'), table_name='idps')
    op.drop_index(op.f('ix_idps_employee_id'), table_name='idps')
    op.drop_table('idps')
    # ### end Alembic commands ###
