"""level framework

Revision ID: d92cc0e629f8
Revises: c98f651f7225
Create Date: 2026-09-29 00:22:58.155997
"""
from alembic import op
import sqlalchemy as sa

import app.models.types


revision = 'd92cc0e629f8'
down_revision = 'c98f651f7225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_framework_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='frameworkstatus'), nullable=False),
    sa.Column('published_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('base_condition_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('level_order', sa.SmallInteger(), nullable=False),
    sa.Column('education_min', sa.String(length=16), nullable=False),
    sa.Column('min_work_years', sa.Integer(), nullable=True),
    sa.Column('min_company_years', sa.Integer(), nullable=True),
    sa.Column('certificates', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['framework_version_id'], ['level_framework_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_version_id', 'level_order', name='base_condition_templates_version_order_uc')
    )
    op.create_index(op.f('ix_base_condition_templates_framework_version_id'), 'base_condition_templates', ['framework_version_id'], unique=False)
    op.create_table('behavior_anchors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['framework_version_id'], ['level_framework_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_version_id', 'code', name='behavior_anchors_version_code_uc')
    )
    op.create_index(op.f('ix_behavior_anchors_framework_version_id'), 'behavior_anchors', ['framework_version_id'], unique=False)
    op.create_table('bonus_item_catalog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('measure_unit', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['framework_version_id'], ['level_framework_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_version_id', 'code', name='bonus_item_catalog_version_code_uc')
    )
    op.create_index(op.f('ix_bonus_item_catalog_framework_version_id'), 'bonus_item_catalog', ['framework_version_id'], unique=False)
    op.create_table('level_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('level_order', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role_definition', sa.Text(), nullable=False),
    sa.Column('performance_level', sa.Text(), nullable=False),
    sa.Column('key_behaviors', sa.JSON(), nullable=False),
    sa.Column('influence_scope', sa.Text(), nullable=False),
    sa.Column('target_anchor', sa.String(length=8), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['framework_version_id'], ['level_framework_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_version_id', 'level_order', name='level_definitions_version_order_uc')
    )
    op.create_index(op.f('ix_level_definitions_framework_version_id'), 'level_definitions', ['framework_version_id'], unique=False)
    op.create_table('tenant_level_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('grade_code', sa.String(length=32), nullable=False),
    sa.Column('level_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['framework_version_id'], ['level_framework_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'framework_version_id', 'grade_code', name='tenant_level_mappings_uc')
    )
    op.create_index(op.f('ix_tenant_level_mappings_framework_version_id'), 'tenant_level_mappings', ['framework_version_id'], unique=False)
    op.create_index(op.f('ix_tenant_level_mappings_tenant_id'), 'tenant_level_mappings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_level_mappings_tenant_id'), table_name='tenant_level_mappings')
    op.drop_index(op.f('ix_tenant_level_mappings_framework_version_id'), table_name='tenant_level_mappings')
    op.drop_table('tenant_level_mappings')
    op.drop_index(op.f('ix_level_definitions_framework_version_id'), table_name='level_definitions')
    op.drop_table('level_definitions')
    op.drop_index(op.f('ix_bonus_item_catalog_framework_version_id'), table_name='bonus_item_catalog')
    op.drop_table('bonus_item_catalog')
    op.drop_index(op.f('ix_behavior_anchors_framework_version_id'), table_name='behavior_anchors')
    op.drop_table('behavior_anchors')
    op.drop_index(op.f('ix_base_condition_templates_framework_version_id'), table_name='base_condition_templates')
    op.drop_table('base_condition_templates')
    op.drop_table('level_framework_versions')
    sa.Enum(name='frameworkstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
