"""talent_succession

Revision ID: dcedd2ea1fa6
Revises: 070d60b1b9d5
Create Date: 2026-09-29 08:28:33.638973
"""
from alembic import op
import sqlalchemy as sa

import app.models.types


revision = 'dcedd2ea1fa6'
down_revision = '070d60b1b9d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dept_id', sa.String(length=32), nullable=True),
    sa.Column('sequence', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('incumbent_employee_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incumbent_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_positions_tenant_id'), 'core_positions', ['tenant_id'], unique=False)
    op.create_table('talent_pools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('pool_level', sa.Enum('L1', 'L2', 'L3', name='poollevel'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('joined_by', sa.Uuid(), nullable=False),
    sa.Column('joined_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'GRADUATED', 'EXITED', name='poolstatus'), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'employee_id', 'pool_level', name='talent_pools_tenant_employee_level_uc')
    )
    op.create_index(op.f('ix_talent_pools_employee_id'), 'talent_pools', ['employee_id'], unique=False)
    op.create_index(op.f('ix_talent_pools_tenant_id'), 'talent_pools', ['tenant_id'], unique=False)
    op.create_table('succession_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('core_position_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.Enum('AUTO', 'MANUAL', name='candidateorigin'), nullable=False),
    sa.Column('willingness', sa.Enum('UNCONFIRMED', 'WILLING', 'UNWILLING', name='willingness'), nullable=False),
    sa.Column('willingness_confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('willingness_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['core_position_id'], ['core_positions.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('core_position_id', 'employee_id', name='succession_candidates_position_employee_uc')
    )
    op.create_index(op.f('ix_succession_candidates_core_position_id'), 'succession_candidates', ['core_position_id'], unique=False)
    op.create_index(op.f('ix_succession_candidates_employee_id'), 'succession_candidates', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_succession_candidates_employee_id'), table_name='succession_candidates')
    op.drop_index(op.f('ix_succession_candidates_core_position_id'), table_name='succession_candidates')
    op.drop_table('succession_candidates')
    op.drop_index(op.f('ix_talent_pools_tenant_id'), table_name='talent_pools')
    op.drop_index(op.f('ix_talent_pools_employee_id'), table_name='talent_pools')
    op.drop_table('talent_pools')
    op.drop_index(op.f('ix_core_positions_tenant_id'), table_name='core_positions')
    op.drop_table('core_positions')
    sa.Enum(name='candidateorigin').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='willingness').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='poollevel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='poolstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
